version = 0.1

[default.deploy.parameters]
stack_name = "fintracker-auth"
resolve_s3 = true
s3_prefix = "fintracker-auth"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "us-east-1"
